### PR TITLE
fix yum epel param in defaults

### PR DESCRIPTION
**Pull request by gthieleb**

### CODE REVIEW

**Comment by jtyr** [comment]
Thanks for opening this PR. Unfortunately the fix is not right. The error is coming from badly named variable `open_vm_tools_epel_yumrepo_params`. Please rename it to `qpid_cpp_server_epel_yumrepo_params` and pust update to this PR and I will merge it.

**Comment by gthieleb** [comment]
Hm, without this fix I get the following error:

	TASK [qpid_cpp_server : Add EPEL YUM repo] ************************************************************************************************************************************************************************
	fatal: [pulp-test]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'qpid_cpp_server_epel_yumrepo_params' is undefined\n\nThe error appears to have been in '/data/development/ansible/roles/qpid_cpp_server/tasks/main.yaml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add EPEL YUM repo\n  ^ here\n"}

**Comment by gthieleb** [comment]
OK, got it! PR comes soon...

**Comment by jtyr** [comment]
Next time you can just create another commit and push it into the same branch and it will update the same PR. Like that you down't have to close the PR and open a new one.

**Comment by gthieleb** [comment]
The PR gets deleted when I removed the commit and forced pushed. But of course you are right, this shouldn't be neccessary at all!

**Comment by jtyr** [comment]
Next time, you can try to amend the commit and then push:

```
# Fork the repo ...
# Clone the repo
$ git clone git@github.com:gthieleb/ansible-qpid_cpp_server.git
$ cd ansible-qpid_cpp_server
# Create new branch
$ git checkout -b gthieleb-qpid
# Edit files ...
# Commit and push
$ git commit -am "Fixing variable"
$ git push -u origin gthieleb-qpid
# Create PR ...
# Do additional change ...
# Amend the commit
$ git commit -a --amend
# Push changes - this will update PR
$ git push
```

Or instead of amending, you can do another commit and then push it.

**Pull request closed without merging**
